name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@releases/v7  # v7 is not released yet; will it fix macOS build issues?
    - uses: cachix/cachix-action@v3  # This also runs nix-build.
      with:
        name: srid
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
